### ISSUE TITLE
Update `flutter_svg` package version

### ISSUE THREAD

**Issue by pedromassango** [roipeker/graphx#16]
The current used version prevent users to build the  example project due to missing `nullOk` parameter missing in the Framework, this was fixed in the latest version of that package.

### Proposal

Update `flutter_svg` version

**Comment by roipeker** [comment]
Sure thing, will do! I didn't have time to even test nullsafety branch yet.

**Comment by pedromassango** [comment]
> Sure thing, will do! I didn't have time to even test nullsafety branch yet.

Is the sample project in nullsafety yet? I think that may cover most of the cases.

**Comment by roipeker** [comment]
Nope, not yet. Didn't have the time.

**Comment by roipeker** [comment]
Just published the update... Im closing the issue
