### ISSUE TITLE
Wish the name was different

### ISSUE THREAD

**Issue by animator** [roipeker/graphx#18]
I came across this package recently and it is awesome, but deep down I always feel that it should have had a different name.

Whenever I hear the term `graphx` the first thing that comes to my mind is network theory (search `networkx`) and graph data structures. There is also a popular library named [graphx](https://spark.apache.org/docs/2.1.0/graphx-programming-guide.html) which does the same.

Please note that this is just a personal opinion and I know it is too late to change the name. Also, the logic of deriving this name must have had origin in `charts and graphs`, but this library is much more than that. I just wanted to let you know as I was expecting something to do with graph algortihms in dart when I first heard about this package.

Awesome work. Good luck 👍

**Comment by roipeker** [comment]
Haha i know what you mean, realized about the other graphx too late though.
Originally graphx was meant to be an extension on getx, plus its all about rendering and i started with the Graphics API 😜, also the logo was _graph.x_ referring to the Cartesian coordinates concept it uses from Flash.

**Comment by animator** [comment]
Nice to know about the origin story. I was not familiar with programming in Flash. 😌

**Comment by roipeker** [comment]
Will close the issue. If come up with a good name, let us know 😃. We might do it one day, like Flare was renamed to Rive...
