### ISSUE TITLE
Does it support zoom and pan?

### ISSUE THREAD

**Issue by shujaatak** [roipeker/graphx#19]

**Comment by roipeker** [comment]
No multipointer/gestures support inside graphx, only the basic mouse interactions. All GDisplayObjects have onMouseDown,onMouseUp, etc. So pan can be easily approached manually inside graphx (or use startDrag(),stopDrag()) but for gestures and multitouch you need a GestureDetector wrapping the SceneBuilderWidget and emitting events to be captured inside graphx code.

**Comment by JulianBissekkou** [comment]
Is support for gestures planned? If not can this be added to the docs? I am sure this will be frequently asked question :o

**Comment by roipeker** [comment]
No plans for now, is totally doable but is just a layer on top of gesture detector. If u put a GestureDetector on top of the SceneBuilderWidget coordinates will match the stage, and you can emit signals to your Graphx scene to use the data.

**Comment by imiskolee** [comment]
@JulianBissekkou if you are working on it, please update any solutions. I also want them. thank you!

**Comment by JulianBissekkou** [comment]
@imiskolee I am not working on it, but I am sure that there is an example where you can check the code. Am i right @roipeker ?
I saw a map example a few months ago on twitter. Can you publish that?

**Comment by roipeker** [comment]
I can't publish the map example, but i can add a simple demo that shows pan and zoom.

is just a matter of notify the gesture detector widget callbacks into the Graphx scene

**Comment by imiskolee** [comment]
@roipeker  it's also very helpful for US!  please a GIST!

**Comment by roipeker** [comment]
[Live demo ](https://graphx-gesture-sample.surge.sh)

[Complete gist](https://gist.github.com/roipeker/000fee572fe2f575774d39aad4965772).

Just made a full sample, might look overcomplicated, but covers Image shader fill (graphics.beginBitmapFill with Matrix transforms), mouse / touch input, and easing.

Hope it makes sense...

**Comment by roipeker** [comment]
> [Live demo ](https://graphx-gesture-sample.surge.sh)
> 
> [Complete gist](https://gist.github.com/roipeker/000fee572fe2f575774d39aad4965772).
> 
> Just made a full sample, might look overcomplicated, but covers Image shader fill (graphics.beginBitmapFill with Matrix transforms), mouse / touch input, and easing.
> 
> Hope it makes sense...

Sorry, I should have provided a simpler sample.
Here's another [gists](https://gist.github.com/roipeker/169351b6591ffaba82c88e8c3f90f167) with much less code.
[live demo ](https://graphx-gesture-simple.surge.sh/#/).

Let me know if the example is clear enough, so i can close this bug report.

**Comment by shujaatak** [comment]
@roipeker Can you please add these gists as examples in the repository? It would really help new comers as they would find the examples in one place rather than scattered around in gists. 

@roipeker GraphX is extremely useful library. Thank you so much for the precious countless hours and neurons you have spent on making this library possible.

**Comment by roipeker** [comment]
Fixed in https://github.com/roipeker/graphx/tree/dedf6cc8f455e4c6213e62731879b8d1aab381d3
