### ISSUE TITLE
Game pad 

### ISSUE THREAD

**Issue by gedw99** [roipeker/graphx#21]
Am thinking about trying to make a game .

anyone know of a flutter package that works with gamepads ?

**Comment by roipeker** [comment]
Sorry @gedw99, no idea.
If you have any doubts about GraphX, i'm happy to help you. You can join the GraphX communication channels if you wanna ask around to other users ([Telegram](https://t.me/joinchat/HHECbrdg4e5U8hH5): , [Discord](https://discord.gg/zKNmHGkn) ) , or maybe check [Flame's](https://github.com/flame-engine/flame) community.

**Comment by gedw99** [comment]
It’s cool 

I know realise dpad is easy.
Gamepad with Bluetooth hookup is hard. Am researching support for the various OS / gamepads

**Comment by gedw99** [comment]
https://github.com/flame-engine/flame_gamepad
android only
