### ISSUE TITLE
how to disable the partent scrollview

### ISSUE THREAD

**Issue by imiskolee** [roipeker/graphx#24]
Hi:

i am have a scenebuildwidget on a singlechildscrollview, and when I drag a shape, the singlechildscrollview also following hand scroll.

I don't know how to disable the  singlechildscrollview when I drag something.

**Comment by roipeker** [comment]
You might have to deal with that on the Flutter side.
Probably some callback or ValueNotifier, Signal, MPS, callback or whatever u can use when u drag something on the Graphx side and rebuild the SingleChildScrollView widget with physics: NeverScrollablePhysics

**Comment by imiskolee** [comment]
got it. thanks!
