### ISSUE TITLE
Thinking of addChildAt

### ISSUE THREAD

**Issue by imiskolee** [roipeker/graphx#29]
Hi:

I know we current has the API `addChildAt` for define z-index, but the max value must less than children.length.
The limit not friendly build a UI keep it last layer if dynamic add children.

So, I am thinking we can define the `Index` same as CSS `z-index`, we can define any int, and just sort  children with the `index` when rending, I also do something before on Myself SVG render engine.

**Comment by roipeker** [comment]
you can't insert a child at random index, if that index is outside the length of the children's List.

If you need custom sorting for the children, you can use any property that you want in the comparison callback of Sprite.sortChildren().
Does that work for you?

**Comment by imiskolee** [comment]
got it,  looks the `sortChildren` is what I need, let me try it first.
