### ISSUE TITLE
Support for web?

### ISSUE THREAD

**Issue by sohan99** [roipeker/graphx#37]
I see most of the examples here support web.
in pub.dev it does not have web support
![Screenshot 2021-09-29 at 2 32 46 PM](https://user-images.githubusercontent.com/9268514/135237764-dbf15ea5-d9fb-41e5-bf55-c2b78e94c13a.png)

**Comment by roipeker** [comment]
Web works fine. I don't know it shows as unsupported.

**Comment by tlvenn** [comment]
That would be the culprit: https://github.com/roipeker/graphx/blob/master/lib/src/utils/http/_http_io.dart#L1

**Comment by tlvenn** [comment]
So to fix this, it seems we need to leverage https://pub.dev/packages/http at the price of adding one more dependency.
If we are ok with this @roipeker , I can open a PR.

**Comment by roipeker** [comment]
Yep, go for it, cant remember why i avoided the dependency
