### ISSUE TITLE
GDisplayObject.requiresRedraw is a noop

### ISSUE THREAD

**Issue by tlvenn** [roipeker/graphx#41]
Hi @roipeker ,

Unless I am missing something, `requiresRedraw` is missing an implementation, in its current form it does nothing
![image](https://user-images.githubusercontent.com/3340262/155636783-57b97968-82e5-4093-b408-949214ae0771.png)

I guess that's probably why there is a TODO 😄

**Comment by roipeker** [comment]
Maybe misleading name, but it sets the basic flags to avoid rendering on the rendereable display objects. As en early optimization basically

**Comment by tlvenn** [comment]
ha got it, the naming indeed but me on the wrong path. I did not have any issue with this, I just came across that piece of code and though it was odd.

Thanks for the clarification.
