### ISSUE TITLE
ScenePainter._detectMouseMove() should be optional

### ISSUE THREAD

**Issue by tlvenn** [roipeker/graphx#44]
There are many situations where you simply don't need to detect mouseover mouseout events when the mouse is still but objects are moving or being hidden / displayed.

The issue is that I soon as you have a ticker, this will feed the system with `still` events every 16ms where the system will traverse the whole graph of object and proceed to do some hit test on them. This is expensive and should be avoided when you actually don't need it.

We should have a flag in the stage to turn this off.

**Comment by roipeker** [comment]
I think we do no? stage.mouseEnabled=false

**Comment by tlvenn** [comment]
But I want mouse events 😄 
This flag `stage.mouseEnabled=false` completely turns off mouse events handling.

**Comment by roipeker** [comment]
Do you have any proposal for the flag name at stage level?
Basically to not compute mouse events on each tick, but only when the Signals arrives ?

**Comment by tlvenn** [comment]
ha naming things.... 😅

**Comment by tlvenn** [comment]
`mouseEnableStillEvents` maybe ? This is probably the most straightforward name even though it does not convey ultimately what it actually achieve...

I tried to come up with a concise name that would explain what this is achieving but failed..

**Comment by tlvenn** [comment]
With proper comment on the flag this should be relatively ok I believe.

**Comment by roipeker** [comment]
Maybe stage.trackMouseHitTest ?

**Comment by tlvenn** [comment]
The problem is even if this is false, we still do track mousehit mouseover mouseout when the mouse actually move so this would end up being pretty misleading.

So maybe `stage.trackStillMouseHitTest` ? 🤔

**Comment by roipeker** [comment]
stage.trackMouseOnTick ?

**Comment by tlvenn** [comment]
Sure thing i will push a PR no worry about that.

**Comment by tlvenn** [comment]
Submitted a tiny PR to add the flag.

**Comment by roipeker** [comment]
Thanks for the contributions @tlvenn !
