### ISSUE TITLE
How many layers can it handle

### ISSUE THREAD

**Issue by gedw99** [roipeker/graphx#5]
Scene layers can only be back or front, according to the docs and code. You can’t have more ?

I am wanting to build graphics editors with graphx and that requires many layers  for example a vector editor like svg edit or a game editor.

**Comment by roipeker** [comment]
Didnt run a stress test to be honest. And i doubt you need so many layers... usually, i just use 1 SceneController for all my rendering... beware that each SceneBuilderWidget creates its own "Graph" with a CustomPainter and Ticker.

if you need help with anything, please let me know.
