### ISSUE TITLE
No code hint?

### ISSUE THREAD

**Issue by miaosun009** [roipeker/graphx#7]
Why is there no code prompt? It's important that there are so many apis, and it's not an editor problem, I tried idea and VsCode

![截屏2020-12-18 上午2 11 50](https://user-images.githubusercontent.com/17589354/102526301-6f55b900-40d6-11eb-9d92-74a18b4d314c.png)

**Comment by roipeker** [comment]
I have no idea why thats happening. Never happened to me. You can search for the Sprite class and the IDE finds it?

**Comment by unacorbatanegra** [comment]
Your problem is independent of graphx, you will have the same issue with others libraries, check the Intellij [documentation](https://www.jetbrains.com/help/idea/auto-completing-code.html). 
GraphX doesn't have a custom configuration of that.
